package com.cloud.eurekaclient.user.dao;

import com.cloud.eurekaclient.user.model.City;
import tk.mybatis.mapper.common.Mapper;

import java.util.List;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Jun 17 22:47:22 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Jun 17 22:47:22 CST 2019
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Jun 17 22:47:22 CST 2019
     */
    City selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Jun 17 22:47:22 CST 2019
     */
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Mon Jun 17 22:47:22 CST 2019
     */
    int updateByPrimaryKey(City record);
}